### ISSUE TITLE
SSL: CERTIFICATE_VERIFY_FAILED

### ISSUE THREAD

**Issue by Matthiator** [omniga-gmbh-co-kg/cinder-easy-backup#1]
First of all thank you for sharing this great tool. We recently switched from http to https endoints. Is there a chance to use https api enpoint connections? Because when trying to connect to an https endpoint, I get the following error:

```
Traceback (most recent call last):
  File "/opt/tools/cinder-easy-backup/venv/lib/python3.6/site-packages/urllib3/connectionpool.py", line 603, in urlopen
    chunked=chunked)
  File "/opt/tools/cinder-easy-backup/venv/lib/python3.6/site-packages/urllib3/connectionpool.py", line 344, in _make_request
    self._validate_conn(conn)
  File "/opt/tools/cinder-easy-backup/venv/lib/python3.6/site-packages/urllib3/connectionpool.py", line 843, in _validate_conn
    conn.connect()
  File "/opt/tools/cinder-easy-backup/venv/lib/python3.6/site-packages/urllib3/connection.py", line 370, in connect
    ssl_context=context)
  File "/opt/tools/cinder-easy-backup/venv/lib/python3.6/site-packages/urllib3/util/ssl_.py", line 355, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/lib/python3.6/ssl.py", line 407, in wrap_socket
    _context=self, _session=session)
  File "/usr/lib/python3.6/ssl.py", line 817, in __init__
    self.do_handshake()
  File "/usr/lib/python3.6/ssl.py", line 1077, in do_handshake
    self._sslobj.do_handshake()
  File "/usr/lib/python3.6/ssl.py", line 689, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/tools/cinder-easy-backup/venv/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/opt/tools/cinder-easy-backup/venv/lib/python3.6/site-packages/urllib3/connectionpool.py", line 641, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/opt/tools/cinder-easy-backup/venv/lib/python3.6/site-packages/urllib3/util/retry.py", line 399, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='placeholderdomain.de', port=5000): Max retries exceeded with url: /v3/auth/tokens (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)'),))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/tools/cinder-easy-backup/venv/lib/python3.6/site-packages/keystoneauth1/session.py", line 979, in _send_request
    resp = self.session.request(method, url, **kwargs)
  File "/opt/tools/cinder-easy-backup/venv/lib/python3.6/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/tools/cinder-easy-backup/venv/lib/python3.6/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/opt/tools/cinder-easy-backup/venv/lib/python3.6/site-packages/requests/adapters.py", line 514, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='placeholderdomain.de', port=5000): Max retries exceeded with url: /v3/auth/tokens (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)'),))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/tools/cinder-easy-backup/cinder-easy-backup.py", line 58, in <module>
    projects = promoteToIndex(cloud.list_projects(), 'name')
  File "/opt/tools/cinder-easy-backup/venv/lib/python3.6/site-packages/shade/openstackcloud.py", line 914, in list_projects
    if self._is_client_version('identity', 3):
  File "/opt/tools/cinder-easy-backup/venv/lib/python3.6/site-packages/shade/openstackcloud.py", line 564, in _is_client_version
    client = getattr(self, client_name)
  File "/opt/tools/cinder-easy-backup/venv/lib/python3.6/site-packages/shade/openstackcloud.py", line 620, in _identity_client
    'identity', min_version=2, max_version='3.latest')
  File "/opt/tools/cinder-easy-backup/venv/lib/python3.6/site-packages/shade/openstackcloud.py", line 510, in _get_versioned_client
    if adapter.get_endpoint():
  File "/opt/tools/cinder-easy-backup/venv/lib/python3.6/site-packages/keystoneauth1/adapter.py", line 282, in get_endpoint
    return self.session.get_endpoint(auth or self.auth, **kwargs)
  File "/opt/tools/cinder-easy-backup/venv/lib/python3.6/site-packages/keystoneauth1/session.py", line 1200, in get_endpoint
    return auth.get_endpoint(self, **kwargs)
  File "/opt/tools/cinder-easy-backup/venv/lib/python3.6/site-packages/keystoneauth1/identity/base.py", line 380, in get_endpoint
    allow_version_hack=allow_version_hack, **kwargs)
  File "/opt/tools/cinder-easy-backup/venv/lib/python3.6/site-packages/keystoneauth1/identity/base.py", line 271, in get_endpoint_data
    service_catalog = self.get_access(session).service_catalog
  File "/opt/tools/cinder-easy-backup/venv/lib/python3.6/site-packages/keystoneauth1/identity/base.py", line 134, in get_access
    self.auth_ref = self.get_auth_ref(session)
  File "/opt/tools/cinder-easy-backup/venv/lib/python3.6/site-packages/keystoneauth1/identity/generic/base.py", line 208, in get_auth_ref
    return self._plugin.get_auth_ref(session, **kwargs)
  File "/opt/tools/cinder-easy-backup/venv/lib/python3.6/site-packages/keystoneauth1/identity/v3/base.py", line 184, in get_auth_ref
    authenticated=False, log=False, **rkwargs)
  File "/opt/tools/cinder-easy-backup/venv/lib/python3.6/site-packages/keystoneauth1/session.py", line 1106, in post
    return self.request(url, 'POST', **kwargs)
  File "/opt/tools/cinder-easy-backup/venv/lib/python3.6/site-packages/keystoneauth1/session.py", line 888, in request
    resp = send(**kwargs)
  File "/opt/tools/cinder-easy-backup/venv/lib/python3.6/site-packages/keystoneauth1/session.py", line 983, in _send_request
    raise exceptions.SSLError(msg)
keystoneauth1.exceptions.connection.SSLError: SSL exception connecting to https://placeholderdomain.de:5000/v3/auth/tokens: HTTPSConnectionPool(host='placeholderdomain.de', port=5000): Max retries exceeded with url: /v3/auth/tokens (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)'),))
```

**Comment by mkuf** [comment]
Hello there, 
the keystone client supports https out of the box, so there shouldn't be anything to modify to make it work. We're exclusively using https endpoints in our cloud. 

This seems to be an Issue with the used Certificate itself. 

Does the CName match the URI in OS_AUTH_URL?
Are you using a self signed Certificate?

You can check with: 
`openssl s_client -showcerts -connect placeholderdomain.de:5000`

-Markus

**Comment by Matthiator** [comment]
Thanks for the hint. We checked the certificates and found that part of the certificate was incorrect. We have corrected the mistake and now everything works. Thank you very much
